
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artemis
  namespace: dev
  annotations: 
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: nginx
    ingressClassName: nginx
spec:
  rules:
  - host: artemis.pyrotecnic2.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: artemis-application
            port:
              number: 5000
              